version: 2.0

references:
  container_config: &container_config
    docker:
      - image: circleci/node
    working_directory: ~/priparaDB-firebase

  workspace_root: &workspace_root
      /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  deploy:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install firebase
          command: sudo npm install -g firebase-tools firebase-bolt eslint eslint-plugin-promise
      - restore_cache:
          key: dependency-cache-{{ checksum "functions/package.json" }}
      - run:
          name: Install packages of functions
          command: cd functions && sudo npm install && cd ..
      - save_cache:
          key: dependency-cache-{{ checksum "functions/package.json" }}
          paths:
            - functions/node_modules

      - run:
          name: Build Rule
          command: firebase-bolt database.rules.bolt
      
      - run:
          name: Deploy to firebase
          command: firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
