version: 2.0

references:
  container_config: &container_config
    docker:
      - image: circleci/node
    working_directory: ~/priparaDB-firebase

  workspace_root: &workspace_root
      /tmp/workspace

jobs:
  deploy:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install firebase
          command: sudo npm install -g firebase-tools eslint eslint-plugin-promise
      - restore_cache:
          key: dependency-cache-{{ checksum "functions/package.json" }}
      - run:
          name: Install packages of functions
          command: cd functions && sudo npm install && cd ..
      - save_cache:
          key: dependency-cache-{{ checksum "functions/package.json" }}
          paths:
            - functions/node_modules
      - run:
          name: Deploy to firebase
          command: firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"